### ISSUE TITLE
Sending arbitrary message causes error

### ISSUE THREAD

**Issue by cregeland** [eyesoft/home_assistant_buspro#15]
Hi,

When attempting to send an arbitrary message I get an "unknown error". Looking through the logs i find:

`2024-12-12 00:29:54.385 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140585787478592] Error handling message: Unknown error (unknown_error) User Name from 192.168.1.100 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 816, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        msg.get("variables"), context=context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
    ~~~~~~~~~~~~~~~~~~~~~~^
        ex, continue_on_error, self._log_exceptions or log_exceptions
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/buspro/__init__.py", line 150, in service_send_message
    await generic.run()
  File "/config/custom_components/buspro/pybuspro/devices/generic.py", line 40, in run
    await generic_control.send()
  File "/config/custom_components/buspro/pybuspro/devices/control.py", line 82, in send
    await self._buspro.network_interface.send_telegram(telegram)
  File "/config/custom_components/buspro/pybuspro/transport/network_interface.py", line 41, in send_telegram
    message = self._th.build_send_buffer(telegram)
  File "/config/custom_components/buspro/pybuspro/helpers/telegram_helper.py", line 114, in build_send_buffer
    operate_code_hex = telegram.operate_code.value
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
**_AttributeError: 'list' object has no attribute 'value'_**`

This is the action I am trying to send:

`action: buspro.send_message
metadata: {}
data: {"address": [1,71], "operate_code": [4,78], "payload": [1,100,0,3]}`.

Activating scenes using the same format (using buspro._activate_scene) and activating Universal Switch (buspro._set_universal_switch) works fine.

**Comment by yiannosi** [comment]
hi..

How did you setup the universal switch service?
Trying to copy-paste 

```
Domain: buspro
Service: set_universal_switch
Service Data: {"address": [1,74], "switch_number": 100, "status": 1}
```
The above results in error from the yaml compiler...
